# Generated by Django 3.1.7 on 2023-01-05 07:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20230105_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='constructionupdates',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 12, 43, 35, 793124)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 12, 43, 35, 460276)),
        ),
        migrations.CreateModel(
            name='PropertyTypeMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.properties')),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.propertytypemaster')),
            ],
        ),
    ]
