# Generated by Django 3.1.7 on 2023-01-07 06:28

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20230105_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('content', tinymce.models.HTMLField()),
                ('desc', models.TextField(default='')),
                ('city', models.CharField(choices=[('1', 'birmingham'), ('2', '\tbolton'), ('3', 'leeds'), ('4', 'manchester'), ('5', 'liverpool'), ('6', 'london'), ('7', 'sheffield'), ('8', 'bradford')], max_length=20)),
                ('image_1', models.FileField(upload_to='media/blogs')),
                ('image_2', models.FileField(upload_to='media/blogs')),
                ('pub_date', models.DateField(default=datetime.datetime(2023, 1, 7, 11, 58, 46, 763577))),
            ],
        ),
        migrations.AlterField(
            model_name='constructionupdates',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 7, 11, 58, 46, 758867)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 7, 11, 58, 46, 698146)),
        ),
    ]
