# Generated by Django 3.1.7 on 2023-01-07 07:39

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20230107_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 7, 13, 9, 47, 810174)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='constructionupdates',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 7, 13, 9, 47, 804293)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 7, 13, 9, 47, 763709)),
        ),
    ]
