# Generated by Django 3.1.7 on 2023-01-07 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20230107_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='deposited_price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='city',
            field=models.CharField(choices=[('1', 'birmingham'), ('2', '\tbolton'), ('3', 'leeds'), ('4', 'manchester'), ('5', 'liverpool'), ('6', 'london'), ('7', 'sheffield'), ('8', 'bradford'), ('9', 'preston'), ('10', 'nottingham')], max_length=20),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 7, 23, 34, 51, 811456)),
        ),
        migrations.AlterField(
            model_name='constructionupdates',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 7, 23, 34, 51, 804460)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='city',
            field=models.CharField(choices=[('1', 'birmingham'), ('2', '\tbolton'), ('3', 'leeds'), ('4', 'manchester'), ('5', 'liverpool'), ('6', 'london'), ('7', 'sheffield'), ('8', 'bradford'), ('9', 'preston'), ('10', 'nottingham')], max_length=20),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 7, 23, 34, 51, 729500)),
        ),
    ]
